### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mexvodvilson** [jnganzh/getWalletBalance#4]
At startup, it gives an error. What could be the reason ?

Traceback (most recent call last):
  File "E:\ETH\getWalletBalance-main\main.py", line 10, in <module>
    df_balance = balance.getCurrentBalances()
  File "E:\ETH\getWalletBalance-main\CurrentTokenBalance.py", line 66, in getCurrentBalances
    token_df = self._getTokens()
  File "E:\ETH\getWalletBalance-main\CurrentTokenBalance.py", line 40, in _getTokens
    data = r.json()['data']['items']
TypeError: 'NoneType' object is not subscriptable

**Comment by jnganzh** [comment]
The api call to covalent was probably incorrect and returned a None object

**Comment by mexvodvilson** [comment]
How to fix it?

**Comment by jnganzh** [comment]
did you fill out the covalent api key?

**Comment by mexvodvilson** [comment]
Yes. Registered on https://www.covalenthq.com/ and received a key. Checked the request https://api.covalenthq.com/v1/1/address/{self.address_lst[0]}/balances_v2/?key={API_KEY} . Wallet balances are displayed. In Main.py added the name of the file with the wallet (1.txt)

**Comment by jnganzh** [comment]
I cant seem to replicate your error, maybe there is some edge case in your address. I have updated the code a little but I do not think it will solve your problem. If it does not work and if you do not mind, you could share the address you want to check and I will try it on my end.

**Comment by mexvodvilson** [comment]
Now throws an error: Traceback (most recent call last):
  File "E:\ETH\getWalletBalance-main\main.py", line 6, in <module>
    df_balance = balance.getCurrentBalances()
  File "E:\ETH\getWalletBalance-main\CurrentTokenBalance.py", line 71, in getCurrentBalances
    token_df = self._getTokens()
  File "E:\ETH\getWalletBalance-main\CurrentTokenBalance.py", line 47, in _getTokens
    for item in data:
UnboundLocalError: local variable 'data' referenced before assignment

**Comment by mexvodvilson** [comment]
address: 0x971A7ADfE0A4803eB2e47667B0dA0757D800be77

**Comment by jnganzh** [comment]
yeah, there is something wrong with your api call

**Comment by jnganzh** [comment]
sorry that was my bad I updated the code wrongly, works now on my end

**Comment by jnganzh** [comment]
[TokenBalances_20210902.csv](https://github.com/jnganzh/getWalletBalance/files/7097173/TokenBalances_20210902.csv)

**Comment by mexvodvilson** [comment]
Very good

**Comment by mexvodvilson** [comment]
I downloaded the latest update. Still the same error:
Traceback (most recent call last):
  File "E:\ETH\getWalletBalance-main\main.py", line 10, in <module>
    df_balance = balance.getCurrentBalances()
  File "E:\ETH\getWalletBalance-main\CurrentTokenBalance.py", line 71, in getCurrentBalances
    token_df = self._getTokens()
  File "E:\ETH\getWalletBalance-main\CurrentTokenBalance.py", line 47, in _getTokens
    for item in data:
UnboundLocalError: local variable 'data' referenced before assignment

**Comment by jnganzh** [comment]
There is a problem with your api call, I am not sure why I cannot replicate the problem.

**Comment by mexvodvilson** [comment]
Can you send your completed files to me at mexvodmbu@gmail.com ? I would compare if I did everything right

**Comment by jnganzh** [comment]
what do you mean by completed files?

**Comment by mexvodvilson** [comment]
your working files (main , CurrentTokenBalance)

**Comment by mexvodvilson** [comment]
If it is important, then upon request
https://api.covalenthq.com/v1/1/address/0x971A7ADfE0A4803eB2e47667B0dA0757D800be77/balances_v2/?key=MY API
CosmoCoin
"balance":"235000000000000000000"
And in the file TokenBalances_20210902.csv it is equal 235.0

**Comment by jnganzh** [comment]
my working files are the same except for my api key.

That is because on the blockchains no decimal places are recorded, I have scaled the values to what you would see on etherscan

https://etherscan.io/address/0x971A7ADfE0A4803eB2e47667B0dA0757D800be77

**Comment by mexvodvilson** [comment]
What version of python are you running on?

**Comment by jnganzh** [comment]
3.96

**Comment by mexvodvilson** [comment]
maybe I don’t have any module?

**Comment by mexvodvilson** [comment]
Or maybe I am not filling in main.py correctly?

**Comment by mexvodvilson** [comment]
I found my mistake !!!

**Comment by jnganzh** [comment]
nice! what was it?

**Comment by mexvodvilson** [comment]
I thought that main.py takes the address from the file and wrote address_lst = ['1.txt']

**Comment by mexvodvilson** [comment]
but it was necessary
 address_lst = ['0x971A7ADfE0A4803eB2e47667B0dA0757D800be77']

**Comment by mexvodvilson** [comment]
can you do that you would take an address from a file with several addresses and for each address with tokens create a file "address".csv ?

**Comment by jnganzh** [comment]
yeah you just would have to change the code up a little

**Comment by mexvodvilson** [comment]
I don’t do as well as you
